# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.MEDSOS.example.com:
  peer1.MEDSOS.example.com:
  peer0.BFF.example.com:
  peer1.BFF.example.com:

networks:
  byfn:

services:

  ################################################## 
  ### ORDERER ######################################
  ################################################## 
  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - byfn

  ################################################## 
  ### MEDSOS ORGANISATION PEERS ####################
  ################################################## 
  peer0.MEDSOS.example.com:
    container_name: peer0.MEDSOS.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.MEDSOS.example.com
    networks:
      - byfn

  peer1.MEDSOS.example.com:
    container_name: peer1.MEDSOS.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.MEDSOS.example.com
    networks:
      - byfn

  ################################################## 
  ### BFF ORGANISATION PEERS #######################
  ################################################## 
  peer0.BFF.example.com:
    container_name: peer0.BFF.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.BFF.example.com
    networks:
      - byfn

  peer1.BFF.example.com:
    container_name: peer1.BFF.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.BFF.example.com
    networks:
      - byfn

  ################################################## 
  ### MEDSOS ORGANISATION ADMIN ####################
  ################################################## 
  medsos_admin:
    container_name: medsos_admin
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/go/bin:/opt/gopath/bin:/opt/gopath/src/github.com/hyperledger/fabric/peer/bin
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=medsos_admin
      - CORE_PEER_ADDRESS=peer0.MEDSOS.example.com:7051
      - CORE_PEER_LOCALMSPID=MEDSOSMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/MEDSOS.example.com/peers/peer0.MEDSOS.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/MEDSOS.example.com/peers/peer0.MEDSOS.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/MEDSOS.example.com/peers/peer0.MEDSOS.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/MEDSOS.example.com/users/Admin@MEDSOS.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        ### HOMEMADE VOLUMES ###
        - /Users/jle-quel/Documents/Go:/opt/gopath
        - ../wallet:/opt/gopath/src/github.com/hyperledger/fabric/peer
        ### BASIC VOLUMES ###
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.MEDSOS.example.com
      - peer1.MEDSOS.example.com
      - peer0.BFF.example.com
      - peer1.BFF.example.com
    networks:
      - byfn

  ################################################## 
  ### BFF ORGANISATION ADMIN #######################
  ################################################## 
  bff_admin:
    container_name: bff_admin
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/go/bin:/opt/gopath/bin:/opt/gopath/src/github.com/hyperledger/fabric/peer/bin
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=bff_admin
      - CORE_PEER_ADDRESS=peer0.BFF.example.com:7051
      - CORE_PEER_LOCALMSPID=BFFMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/BFF.example.com/peers/peer0.BFF.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/BFF.example.com/peers/peer0.BFF.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/BFF.example.com/peers/peer0.BFF.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/BFF.example.com/users/Admin@BFF.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        ### HOMEMADE VOLUMES ###
        - /Users/jle-quel/Documents/Go:/opt/gopath
        - ../wallet:/opt/gopath/src/github.com/hyperledger/fabric/peer
        ### BASIC VOLUMES ###
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.MEDSOS.example.com
      - peer1.MEDSOS.example.com
      - peer0.BFF.example.com
      - peer1.BFF.example.com
    networks:
      - byfn
